name: Deploy to Azure ML

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: checking the current directory & contents & path
        run: |
          pwd
          ls -ltra
          df -h

      - name: Run Pipeline
        run: python pipeline.py

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Model
        run: |
          az ml model create --name cardio-model --path ./models/cardio_model.pkl --resource-group mlopsrg --workspace-name risk-ml || echo "Model creation failed"

      - name: Create or Update Endpoint
        run: |
          if az ml online-endpoint show --name cardio-endpoint --resource-group mlopsrg --workspace-name risk-ml > /dev/null 2>&1; then
            echo "Endpoint exists, updating..."
            az ml online-deployment update --file webapp/deployment.yaml --resource-group mlopsrg --workspace-name risk-ml || echo "Update failed"
          else
            echo "Endpoint does not exist, creating..."
            az ml online-endpoint create --name cardio-endpoint --resource-group mlopsrg --workspace-name risk-ml || echo "Creation failed"
            az ml online-deployment create --file webapp/deployment.yaml --resource-group mlopsrg --workspace-name risk-ml || echo "Deployment failed"
          fi
