name: Deploy to Azure ML

on:
  push:
    branches:
      - main
      - feature/enable-swagger-ui

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Check directory & contents
        run: |
          pwd
          ls -ltra
          df -h

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Azure ML Pipeline
        run: python src/pipeline.py
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          # Add Azure ML workspace config as environment variables
          AZUREML_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZUREML_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZUREML_WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}
          AZUREML_LOCATION: ${{ secrets.AZURE_LOCATION }}